//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliver.ProductOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportMap
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string Name { get; set; }
        public bool SkipFirstRow { get; set; }
        public int C_CompanyProductIdI { get; set; }
        public int C_NameI { get; set; }
        public Nullable<int> C_SkuI { get; set; }
        public Nullable<int> C_PriceI { get; set; }
        public Nullable<int> C_DescriptionI { get; set; }
        public Nullable<int> C_CategoryI { get; set; }
        public int CurrencyId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
