//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliver.DataSifter {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HighlightHtmlTags {
            get {
                return ((bool)(this["HighlightHtmlTags"]));
            }
            set {
                this["HighlightHtmlTags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PrintCaptureLabels {
            get {
                return ((bool)(this["PrintCaptureLabels"]));
            }
            set {
                this["PrintCaptureLabels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IndianRed")]
        public global::System.Drawing.Color HtmlTagsColor {
            get {
                return ((global::System.Drawing.Color)(this["HtmlTagsColor"]));
            }
            set {
                this["HtmlTagsColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkCyan")]
        public global::System.Drawing.Color HtmlCommentColor {
            get {
                return ((global::System.Drawing.Color)(this["HtmlCommentColor"]));
            }
            set {
                this["HtmlCommentColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial, 6.75pt, style=Bold")]
        public global::System.Drawing.Font CaptureLabelFont {
            get {
                return ((global::System.Drawing.Font)(this["CaptureLabelFont"]));
            }
            set {
                this["CaptureLabelFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StripParsedTextInStatusBarFromHtmlTags {
            get {
                return ((bool)(this["StripParsedTextInStatusBarFromHtmlTags"]));
            }
            set {
                this["StripParsedTextInStatusBarFromHtmlTags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfInt xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <int>-3618561</int>
  <int>-18751</int>
  <int>-7278960</int>
  <int>-23222</int>
  <int>-1645056</int>
  <int>-65281</int>
  <int>-16711681</int>
  <int>-8323328</int>
  <int>-4144960</int>
  <int>-8355776</int>
  <int>-65408</int>
  <int>-16711808</int>
  <int>-16744193</int>
  <int>-65281</int>
  <int>-12550016</int>
  <int>-1609704</int>
  <int>-256</int>
  <int>-8388480</int>
  <int>-16744320</int>
  <int>-16776961</int>
  <int>-65536</int>
</ArrayOfInt>")]
        public int[] FilterMarkColorsRGB {
            get {
                return ((int[])(this["FilterMarkColorsRGB"]));
            }
            set {
                this["FilterMarkColorsRGB"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DataSifter.chm")]
        public string HelpFile {
            get {
                return ((string)(this["HelpFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.cliversoft.com/products/regextreeer/2.5/help/index.htm")]
        public string HelpFileUri {
            get {
                return ((string)(this["HelpFileUri"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MidnightBlue")]
        public global::System.Drawing.Color FilterCommentColor {
            get {
                return ((global::System.Drawing.Color)(this["FilterCommentColor"]));
            }
            set {
                this["FilterCommentColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 0, 0")]
        public global::System.Drawing.Color FilterGroupNameColor {
            get {
                return ((global::System.Drawing.Color)(this["FilterGroupNameColor"]));
            }
            set {
                this["FilterGroupNameColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CopySelectionToClipboard {
            get {
                return ((bool)(this["CopySelectionToClipboard"]));
            }
            set {
                this["CopySelectionToClipboard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OutputGroupNames {
            get {
                return ((bool)(this["OutputGroupNames"]));
            }
            set {
                this["OutputGroupNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MidnightBlue")]
        public global::System.Drawing.Color HtmlJavascriptColor {
            get {
                return ((global::System.Drawing.Color)(this["HtmlJavascriptColor"]));
            }
            set {
                this["HtmlJavascriptColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n##################################\r\n##################################\r\n###\r\n##" +
            "#\r\n###\r\n##################################\r\n##################################\r\n" +
            "")]
        public string OutputDataSeparator {
            get {
                return ((string)(this["OutputDataSeparator"]));
            }
            set {
                this["OutputDataSeparator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSourceFile {
            get {
                return ((string)(this["LastSourceFile"]));
            }
            set {
                this["LastSourceFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastFilterTreeFile {
            get {
                return ((string)(this["LastFilterTreeFile"]));
            }
            set {
                this["LastFilterTreeFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ApplicationVersion {
            get {
                return ((string)(this["ApplicationVersion"]));
            }
            set {
                this["ApplicationVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SourceFormInitialDirectory {
            get {
                return ((string)(this["SourceFormInitialDirectory"]));
            }
            set {
                this["SourceFormInitialDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection _FilterTreeFolder2SourceFolder {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["_FilterTreeFolder2SourceFolder"]));
            }
            set {
                this["_FilterTreeFolder2SourceFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>RegexFilter</string>
  <string>&gt;(?'N'.*?)&lt;
IgnoreCase, Compiled, Singleline</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection _FilterTypeName2NewFilter {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["_FilterTypeName2NewFilter"]));
            }
            set {
                this["_FilterTypeName2NewFilter"] = value;
            }
        }
    }
}
