//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliver.FhrApi.ProductOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.ImportMaps = new HashSet<ImportMap>();
            this.Products = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string Comment { get; set; }
        public string CrawlerId { get; set; }
    
        public virtual ICollection<ImportMap> ImportMaps { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
