//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliver.FhrApi.ProductOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Prices = new HashSet<Price>();
        }
    
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string ExternalId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string ImageUrls { get; set; }
        public string Sku { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public Nullable<int> LinkId { get; set; }
        public string Source { get; set; }
        public Nullable<decimal> Stock { get; set; }
        public int MainProductId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<Price> Prices { get; set; }
    }
}
